---

- name: Update webservers
  hosts: all
  remote_user: root
  become: yes

  tasks:
    - name: upgrade all packages
      yum: name=* state=latest
    - name: Install git, vim
      yum:
        name: "{{ item }}"
        state: latest
      loop:
        - git
        - vim
        - htop 
        - openssl-devel 
        - libffi-devel 
        - bzip2-devel 
        - wget
    - name: Remove
      yum:
        name: "{{ item }}"
        state: absent
      loop:
          - httpd
          - nginx
          - mysql 
      become: true
    - name: download sources
      shell: 
        - echo "asd"
        - hostname
    - name: download sources
      get_url: url="https://www.python.org/ftp/python/3.9.5/Python-3.9.5.tgz"
    # - name: make
      # shell: groupinstall "Development Tools" -y
    # - name: Install git, vim
    #   yum:
    #     name:
    #       - openssl-devel
    #       - libffi-devel
    #       - bzip2-devel
    #     state: latest
    # - name: PIP install
    #   pip:
    #     name:
    #       - pyTelegramBotAPI
    #       - six
    #     executable: pip3
    #     state: present
