---

- name: Update webservers
  hosts: all
  remote_user: root
  become: yes

  tasks:
    - name: Install git, vim
      yum:
        name: "{{ item }}"
        state: latest
      becomde: yes
      with_item: 
        - yum-install
        - lvm2
        - device-mapper-presistent-data
    - name: Install Python3
      yum:
        name:
          - python3.7-six
          - python3.7-pip
          - python3.7
          - python3.7-setuptools
        state: latest
    - name: PIP install
      pip:
        name:
          - pyTelegramBotAPI
          - six
        executable: pip3
        state: present
    - name: Remove python
      yum:
        name:
          - python3-six 
          - python3 
          - python3-setuptools 
        state: absent
      become: true