---

- name: Update webservers
  hosts: all
  remote_user: root
  become: yes

  tasks:
    - name: Install git, vim
      yum:
        name:
          - vim
          - git
        state: lates
    - name: Install Python3
      yum:
        name:
          - python3-six
          - python3-pip
          - python3
          - python3-setuptools
        state: latest
    - name: PIP install
      pip:
        name:
          - pyTelegramBotAPI
          - six
        executable: pip3
        state: present
    - name: Remove python
      yum:
        pkg: python 
        pkg: python-pip 
        pkg: python-setuptools 
        state: absent
      become: true