---

- name: Update webservers
  hosts: all
  remote_user: root
  become: yes

  tasks:
    - name: upgrade all packages
      yum: name=* state=latest
    - name: Install packages
      yum:
        name: "{{ item }}"
        state: latest
      becomde: yes
      with_item: 
        - yum-install
        - vim
        - htop
    # - name: PIP install
    #   pip:
    #     name:
    #       - pyTelegramBotAPI
    #       - six
    #     executable: pip3
    #     state: present
    # - name: Remove python
    #   yum:
    #     name:
    #       - python3-six 
    #       - python3 
    #       - python3-setuptools 
    #     state: absent
    #   become: true