---
- name: Deploy
  hosts: all
  become: true

  vars: 
    dir: /opt/
    dir_bot: /opt/py
    docker_image: pybots

  tasks:
  - name: docker python
    yum:
      name: python-docker
      state: latest

  - name: "check {{docker_image}} container"
    docker_container_info:
      name: "{{docker_image}}"
    register: result
  
  - name: Debug
    debug:
      var: result

  - name: Stop a container
    docker_container:
      name: "{{docker_image}}"
      state: stopped

  # - name: Stop a container
  #   docker_container:
  #     name: "{{docker_image}}"
  #     state: absent

  - name: Git checkout
    ansible.builtin.git:
      repo: 'https://github.com/IlfatGub/pybot.git'
      dest: "{{dir_bot}}"
      force: yes

  - name: Docker build
    shell: "docker build -t {{docker_image}} ."
    args:
      chdir: "{{dir_bot}}"

  - name: Docker run
    shell: "docker run -d --rm --mount={{docker_image}} type=bind,src=/opt/py/python,target=/usr/src/app {{docker_image}}"
