---
- name: Deploy
  hosts: all
  become: true

  vars: 
    dir: /opt/
    dir_bot: /opt/py
    docker_image: pybots

  tasks:
  - name: Git checkout
    ansible.builtin.git:
      repo: 'https://github.com/IlfatGub/pybot.git'
      dest: "{{dir_bot}}"
      force: yes
  - name: Docker build
    shell: "/usr/bin/docker build -t {{docker_image}} ."
    args:
      chdir: "{{dir_bot}}"
  - name: Docker run
    shell: "/usr/bin/docker run --rm --name -d --mount type=bind,src=/opt/py/python,target=/usr/src/app {{docker_image}}"
