---

- name: Update 
  hosts: all
  remote_user: root
  become: yes

  tasks:
    - name: ZSH install
      yum:
        name: zsh
    - name: sh
      shell: "curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh"